# Data Cleaning and Panel Construction

This notebook constructs the final country–year panel dataset used in the analysis.

Goals:
- Clean WHO dataset
- Clean World Bank dataset
- Pivot WDI dataset
- Harmonize countries
- Merge datasets
- Inspect missingness
- Apply imputation rules

The output of this notebook is the cleaned analytical dataset saved to `data/processed/`.

### Verifying Project Root
(this step is neccessary given we will have to work with nested directories)

In [1]:
import sys
from pathlib import Path

# find project root (one level above notebooks/)
PROJECT_ROOT = Path().resolve().parents[0]
sys.path.append(str(PROJECT_ROOT / "src"))

print("Project root:", PROJECT_ROOT)

Project root: /Users/rnd4impact/Desktop/RND4IMPACT Projects/life-expectancy-analysis

### Imports

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

from data.data_loading import load_raw, standardize, merge
from data.data_preprocessing import (
    clean_who,
    clean_wb,
    pivot_wdi,
    missingness_table,
    missingness_by_year,
    missingness_by_country,
    impute_panel,
)

### Used Paths

In [3]:
RAW = Path("../data/raw")
PROCESSED = Path("../data/processed")
PROCESSED.mkdir(exist_ok=True)

# Loading standardized datasets

In [4]:
who_path = Path("../data/raw/world_health_organization/who.csv")  
who_raw = load_raw("who", path=who_path)
who = standardize(who_raw, "who")

wb_path = Path("../data/raw/world_bank/wb.csv")  
wb_raw = load_raw("wb", path=wb_path)
wb = standardize(wb_raw, "wb")

wdi_path = Path("../data/raw/world_bank/wdi.csv")  
wdi_raw = load_raw("wdi", path=wdi_path)
wdi = standardize(wdi_raw, "wdi")

## Dataset Cleaning

### WHO

In [6]:
who_clean, who_summary = clean_who(
    who,
    min_years_per_country=10,
    feature_missingness_drop_threshold=0.8
)

who_summary

{'input_rows': 2938,
 'input_cols': 22,
 'duplicate_policy': 'keep_first',
 'min_years_per_country': 10,
 'drop_missing_target': True,
 'feature_missingness_drop_threshold': 0.8,
 'duplicate_rows': 0,
 'rows_after_dedup': 2938,
 'life_expectancy_invalid_count': 0,
 'immunization_cols_clipped': ['hepatitis_b',
  'measles',
  'polio',
  'diphtheria'],
 'rows_dropped_missing_target': 10,
 'rows_dropped_low_coverage': 0,
 'countries_kept': 183,
 'dropped_feature_cols': [],
 'n_dropped_feature_cols': 0,
 'output_rows': 2928,
 'output_cols': 22,
 'year_min': 2000,
 'year_max': 2015}

### WB

In [9]:
wb_clean, wb_summary = clean_wb(
    wb,
    winsorize_cols=["GDP", "CO2"],
    log_transform_cols=["GDP"],
    feature_missingness_drop_threshold=0.7
)

wb_summary

{'input_rows': 3306,
 'input_cols': 16,
 'feature_missingness_drop_threshold': 0.7,
 'winsorize_cols': ['GDP', 'CO2'],
 'log_transform_cols': ['GDP'],
 'dropped_feature_cols': ['corruption'],
 'n_dropped_feature_cols': 1,
 'duplicate_rows': 0,
 'output_rows': 3306,
 'output_cols': 15,
 'year_min': 2001,
 'year_max': 2019}

### WDI Pivotting

In [10]:
wdi_panel, wdi_summary = pivot_wdi(
    wdi,
    indicator_codes=["SP.DYN.LE00.IN"],
    year_min=1950
)

wdi_summary

{'input_rows': 266,
 'rows_after_indicator_filter': 266,
 'n_year_columns': 65,
 'indicator_codes': ['SP.DYN.LE00.IN'],
 'rows_dropped_all_nan': 0,
 'output_rows': 16926,
 'output_cols': 3}

In [11]:
wdi_panel.head()

       country  year  SP.DYN.LE00.IN
0  Afghanistan  1960          32.799
1  Afghanistan  1961          33.291
2  Afghanistan  1962          33.757
3  Afghanistan  1963          34.201
4  Afghanistan  1964          34.673

## WHO + WB Merging

In [21]:
panel, merge_diag = merge(
    who_clean,
    wb_clean,
    how="inner"
)

merge_diag

{'who_rows': 2928,
 'wb_rows': 3306,
 'how': 'inner',
 'on': ('country', 'year'),
 'merged_rows': 2265,
 'who_unique_keys': 2928,
 'wb_unique_keys': 3306,
 'merged_unique_keys': 2265,
 'keys_lost_from_who': 663,
 'keys_lost_from_wb': 1041}

In [15]:
bigger_panel, merge_diag = merge(
    who_clean,
    wb_clean,
    how="outer"
)

merge_diag

{'who_rows': 2928,
 'wb_rows': 3306,
 'how': 'outer',
 'on': ('country', 'year'),
 'merged_rows': 3969,
 'who_unique_keys': 2928,
 'wb_unique_keys': 3306,
 'merged_unique_keys': 3969,
 'keys_lost_from_who': 0,
 'keys_lost_from_wb': 0}

## Missingness Analysis

In [37]:
panel.head()

       country  year  ... communicable  noncommunicable_disease
0  Afghanistan  2015  ...   6528888.62               6988545.28
1  Afghanistan  2014  ...   6649335.87               6900348.40
2  Afghanistan  2013  ...   6813189.19               6799914.37
3  Afghanistan  2012  ...   7036448.02               6640268.93
4  Afghanistan  2011  ...   7181018.86               6539124.12

[5 rows x 35 columns]

In [23]:
miss_table = missingness_table(panel)
miss_table

                             column  ...  non_missing_count
0                        sanitation  ...               1464
1     education_expenditure_percent  ...               1548
2                       hepatitis_b  ...               1860
3                  undernourishment  ...               1935
4                        population  ...               2051
5                 total_expenditure  ...               2089
6                           alcohol  ...               2104
7                      unemployment  ...               2205
8        health_expenditure_percent  ...               2209
9                               gdp  ...               2234
10              thinness_1_19_years  ...               2235
11                              bmi  ...               2235
12               thinness_5_9_years  ...               2235
13  income_composition_of_resources  ...               2250
14                            polio  ...               2250
15                       diphtheria  ...               2250
16                        schooling  ...               2250
17                              co2  ...               2265
18               life_expectancy_wb  ...               2265
19                           region  ...               2265
20                         injuries  ...               2265
21                     communicable  ...               2265
22                     income_group  ...               2265
23                          country  ...               2265
24                     country_code  ...               2265
25                             year  ...               2265
26                         hiv_aids  ...               2265
27                under_five_deaths  ...               2265
28                          measles  ...               2265
29           percentage_expenditure  ...               2265
30                    infant_deaths  ...               2265
31                  adult_mortality  ...               2265
32                  life_expectancy  ...               2265
33                           status  ...               2265
34          noncommunicable_disease  ...               2265

[35 rows x 4 columns]

Missingness by year:

In [33]:
miss_year = missingness_by_year(panel, cols=["life_expectancy_wb"])
miss_year

    year  n_rows  life_expectancy_wb_missing_fraction
0   2001     151                                  0.0
1   2002     151                                  0.0
2   2003     151                                  0.0
3   2004     151                                  0.0
4   2005     151                                  0.0
5   2006     151                                  0.0
6   2007     151                                  0.0
7   2008     151                                  0.0
8   2009     151                                  0.0
9   2010     151                                  0.0
10  2011     151                                  0.0
11  2012     151                                  0.0
12  2013     151                                  0.0
13  2014     151                                  0.0
14  2015     151                                  0.0

Missingness by country:

In [36]:
miss_country = missingness_by_country(panel, cols=["life_expectancy_wb"])
miss_country

             country  n_rows  life_expectancy_wb_missing_fraction
0        Afghanistan      15                                  0.0
1         Mozambique      15                                  0.0
2            Namibia      15                                  0.0
3              Nepal      15                                  0.0
4        Netherlands      15                                  0.0
5        New Zealand      15                                  0.0
6          Nicaragua      15                                  0.0
7              Niger      15                                  0.0
8            Nigeria      15                                  0.0
9             Norway      15                                  0.0
10              Oman      15                                  0.0
11          Pakistan      15                                  0.0
12            Panama      15                                  0.0
13  Papua New Guinea      15                                  0.0
14          Paraguay      15                                  0.0

## Imputation

In [38]:
panel["life_expectancy_final"] = panel[["life_expectancy", "life_expectancy_wb"]].mean(axis=1)
panel.head()

       country  year  ... noncommunicable_disease  life_expectancy_final
0  Afghanistan  2015  ...              6988545.28                64.1885
1  Afghanistan  2014  ...              6900348.40                61.4330
2  Afghanistan  2013  ...              6799914.37                61.2125
3  Afghanistan  2012  ...              6640268.93                60.7770
4  Afghanistan  2011  ...              6539124.12                60.3765

[5 rows x 36 columns]

In [40]:
panel_imputed, impute_summary = impute_panel(
    panel,
    interpolate_cols=["gdp", "health_expenditure_percent", "sanitation"],
    group_cols=["region", "income_group"],
    group_median_cols=["education_expenditure_percent"],
    median_impute_cols=["unemployment", "corruption"],
)

impute_summary

{'input_rows': 2265,
 'interpolate_cols': ['gdp', 'health_expenditure_percent', 'sanitation'],
 'median_impute_cols': ['unemployment', 'corruption'],
 'group_cols': ['region', 'income_group'],
 'group_median_cols': ['education_expenditure_percent'],
 'interpolate_filled_counts': {'gdp': 11,
  'health_expenditure_percent': 9,
  'sanitation': 3},
 'group_median_filled_counts': {'education_expenditure_percent': 717},
 'median_filled_counts': {'unemployment': 60},
 'output_rows': 2265,
 'target_missing_count_after': 0}

In [41]:
panel_imputed.to_csv(PROCESSED / "main_dataset.csv", index=False)